[tools]
"aqua:anthropics/claude-code" = "2.1.233"
"aqua:k1LoW/deck" = "1.24.1"
"aqua:k1LoW/git-wt" = "0.29.1"
"aqua:k1LoW/mo" = "v1.6.7"
"aqua:yukiarrr/ecsk" = "0.9.5"
aws-cli = { version = "2.36.24", symlink_bins = "true" }
aws-vault = "7.9.15"
direnv = "2.37.1"
gh = "2.97.0"
ghq = "1.10.1"
git-lfs = "3.7.1"
"github:microsoft/waza" = "v0.38.6"
glab = { version = "1.92.1", exe = "glab" }
go = "1.27.0"
jq = "1.8.2"
neovim = "0.12.4"
node = "24.19.0"
"npm:ccusage" = "20.0.20"
packer = "1.16.0"
peco = "0.6.0"
"pipx:docling-slim" = "2.120.2"
"pipx:yubikey-manager" = "5.9.2"
pnpm = "11.21.0"
ripgrep = "15.2.0"
sqlite = "3.53.4"
starship = "1.26.0"
uv = "0.12.5"
terraform = "1.15.8"
trivy = "0.73.0"
zellij = "0.44.3"
zoxide = "0.10.0"
ollama = "latest"
"pipx:aider-chat" = "v0.86.2"
"aqua:aws/session-manager-plugin" = "latest"
